spring:
  application:
    name: libro
  datasource:
    url: jdbc:mysql://localhost:3306/bibliotecaferreria
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  messages:
    basename: i18n/messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

server:
  port: 9090

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  paths-to-match: /**

  jwt:
    secret: 8f9a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t